{% set name = "moderngl-window" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7cc0edfebdb556772e62a0461f1c8b90c4ad6b9ab2ccb35935a62027b5f36511

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - moderngl <6
    - numpy >=1.16,<2
    - pillow >=5
    - pyglet >=1.5.8,<2
    - pyrr >=0.10.3,<1
    - python >=3.6

test:
  imports:
    - moderngl_window
    - moderngl_window.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moderngl/moderngl_window
  summary: A cross platform helper library for ModernGL making window creation and resource loading simple
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
