{% set name = "moderngl-window" %}
{% set version = "2.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moderngl-window-{{ version }}.tar.gz
  sha256: 2ee6e80b215ce4e7db5bef8d166010a3f2b9060449688652bfe06fa7c904d01b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - moderngl <6
    - numpy >=1.16,<2
    - pillow >=5
    - pyglet >=1.5.8,<2
    - pyrr >=0.10.3,<1
    - python >=3.6

test:
  imports:
    - moderngl_window
    - moderngl_window.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moderngl/moderngl_window
  summary: A cross platform helper library for ModernGL making window creation and resource loading simple
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
