{% set name = "moderngl-window" %}
{% set version = "2.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moderngl-window-{{ version }}.tar.gz
  sha256: 6e80cbba4102ab8e33902603d9dda0bb52ac9e34d1f565edf61182003373c327

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - moderngl <6
    - pyglet >=2.0
    - numpy >=1.16,<2
    - pyrr >=0.10.3,<1
    - pillow >=9,<10

test:
  imports:
    - moderngl_window
    - moderngl_window.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moderngl/moderngl_window
  summary: A cross platform helper library for ModernGL making window creation and resource loading simple
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
